### PR TITLE
Enable FreeBSD python

### PR DESCRIPTION
**Pull request by benrubson**
Hi,

This enables python on FreeBSD.

Thx 👍

### CODE REVIEW

**Comment by benrubson** [comment]
This `python` meta package properly links `python` / `python3` commands to the installed (3.7) version.

**Comment by benrubson** [comment]
Mmmh strangely enough it worked on my test VM :)
Investigating...

**Comment by benrubson** [comment]
Finally...
And rather generic :)

**Comment by WayneD** [comment]
Almost 5 minutes of prep time? That's horrible.  I think I'll just leave md2man off.

**Pull request closed without merging**
