### PR TITLE
Add manpage explanation for --compres-level values

### PR DESCRIPTION
**Pull request by samueloph**
Hello Wayne,

I'm sending this patch we currently apply in the Debian packaging of rsync, I believe it would be nice to have it upstreamed.

Thanks,

### CODE REVIEW

**Comment by WayneD** [comment]
Sadly, this detail is no longer true since it only applies to zlib compression.

**Comment by samueloph** [comment]
@WayneD thanks, that's good to know, I will remove this one from the Debian package.

**Comment by WayneD** [comment]
I've fleshed out that section of the man page with up-to-date details for 3.2.1.

**Comment by samueloph** [comment]
Awesome! Looking forward for 3.2.1

**Pull request closed without merging**
